# Generated by Django 4.2.7 on 2025-06-29 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontable',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
